--liquibase formatted sql


--changeset nvoxland:3 <comment>fsd
CREATE TABLE IF NOT EXISTS loh2
(
    loh_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name_       VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(1000),
    CONSTRAINT pk_loh2 PRIMARY KEY (loh_id)
);